### ISSUE TITLE
Setup auto deployment of frontend to now.sh on merge to master

### ISSUE THREAD

**Issue by Matthew-Burfield** [chingu-voyages/v16-bears-team-04#23]

**Comment by dastrong** [comment]
this was the reply I got from ZEIT Now regarding Now and GitHub integrations last month:

> Unfortunately, GitHub is not very good in terms of clarity around possible permission errors. We require the owner of the organization to install the integration given how GitHub permission works. Therefore, is not enough to install Now as the owner of the repo and you will need assistance from the org's owner.
